service: 
    name: identity-management-python-example
custom:
  bucket: test-bucket-for-csvs    
provider:
 name: aws
 runtime: python3.6
 memorySize: 128
 timeout: 10
 stage: production
 region: us-east-1
 iamRoleStatements:
    - Effect: Allow
      Action:
       - s3:GetObject
      Resource: arn:aws:s3:::${self:custom.bucket}/*            

functions:
    getUsers: 
        handler: handler.getUsers
        events:
         - s3:
            bucket: ${self:custom.bucket}
            event: s3:ObjectCreated:*
            rules:
              - prefix: idm_events/
              - suffix: getUsers.csv         
    createUsers: 
        handler: handler.createUsers
        events:
         - s3:
            bucket: ${self:custom.bucket}
            event: s3:ObjectCreated:*
            rules:
              - prefix: idm_events/
              - suffix: createUsers.csv
    deleteUsers: 
        handler: handler.deleteUsers
        events:
         - s3:
            bucket: ${self:custom.bucket}
            event: s3:ObjectCreated:*
            rules:
              - prefix: idm_events/
              - suffix: deleteUsers.csv
    findUsers: 
        handler: handler.findUsers
        events:
         - s3:
            bucket: ${self:custom.bucket}
            event: s3:ObjectCreated:*
            rules:
              - prefix: idm_events/
              - suffix: findUsers.csv              
resources:
  Resources:
    CSVBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket}         
      